"""Build the .mcpb bundle: the one-click install path for Claude Desktop.

Why a bundle at all, when setup.bat exists: Windows 11's Smart App Control refuses to
run a batch file that came from a browser, and offers no way through -- no "Run
anyway", nothing. A .mcpb is data, opened by Claude Desktop rather than executed by
Windows, so that wall is never met. The installer stays for machines with no Python and
for its diagnostics; this is the path for everyone else.

The bundle uses the ``uv`` server type: the host resolves Python and the dependencies
in pyproject.toml itself, so the user installs nothing. That is also why the staged
pyproject is generated rather than copied -- the repository's own carries a readme
reference, dev extras and pytest settings that have no meaning inside a bundle.

Run: python scripts/build_mcpb.py    (needs Node for the mcpb CLI; no JDK)
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STAGE = REPO / ".mcpb-build"
DIST = REPO / "dist"
MANIFEST = REPO / "mcpb" / "manifest.json"
ENTRY = REPO / "mcpb" / "server.py"
PACKAGE = REPO / "shamela_mcp"
JAR = REPO / "java" / "shamela-mcp-helper.jar"

MCPB_CLI = "@anthropic-ai/mcpb@latest"

PYPROJECT = """\
# Generated by scripts/build_mcpb.py -- edit the repository's pyproject.toml instead.
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "shamela-mcp"
version = "{version}"
description = "MCP server exposing the local Al-Maktaba Al-Shamela 4 library"
requires-python = ">={python_min}"
dependencies = [
{dependencies}
]

[tool.setuptools]
packages = ["shamela_mcp", "shamela_mcp.tools"]
"""


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def npx(*args: str) -> subprocess.CompletedProcess:
    """Run the mcpb CLI. Node ships with Claude Desktop's audience, not with ours."""
    executable = "npx.cmd" if sys.platform == "win32" else "npx"
    command = [executable, "-y", MCPB_CLI, *args]
    proc = subprocess.run(command, capture_output=True, text=True, encoding="utf-8")
    if proc.returncode != 0:
        print(proc.stdout, file=sys.stderr)
        print(proc.stderr, file=sys.stderr)
        fail(f"mcpb {args[0]} failed")
    return proc


def read_version() -> str:
    text = (PACKAGE / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'__version__\s*=\s*"([^"]+)"', text)
    if match is None:
        fail("no __version__ in shamela_mcp/__init__.py")
    return match.group(1)  # type: ignore[union-attr]


def read_dependencies() -> tuple[list[str], str]:
    """The runtime dependencies and minimum Python, taken from the real pyproject."""
    text = (REPO / "pyproject.toml").read_text(encoding="utf-8")
    block = re.search(r"^dependencies = \[(.*?)\]", text, re.S | re.M)
    if block is None:
        fail("no [project] dependencies in pyproject.toml")
    deps = re.findall(r'"([^"]+)"', block.group(1))  # type: ignore[union-attr]
    python = re.search(r'requires-python\s*=\s*">=([\d.]+)"', text)
    if not deps or python is None:
        fail("could not read dependencies or requires-python from pyproject.toml")
    return deps, python.group(1)  # type: ignore[union-attr]


def stage(version: str) -> None:
    if STAGE.exists():
        shutil.rmtree(STAGE)
    STAGE.mkdir(parents=True)

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    # One version number for the package and the bundle: a manifest that drifts from
    # __version__ makes "which build is running?" unanswerable from the Claude UI.
    manifest["version"] = version
    (STAGE / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    (STAGE / "src").mkdir()
    shutil.copy2(ENTRY, STAGE / "src" / "server.py")

    shutil.copytree(
        PACKAGE, STAGE / "shamela_mcp", ignore=shutil.ignore_patterns("__pycache__", "*.pyc")
    )

    if not JAR.is_file():
        fail(f"helper jar missing: {JAR}. Build it with scripts/build_java.py")
    (STAGE / "java").mkdir()
    shutil.copy2(JAR, STAGE / "java" / JAR.name)

    for name in ("README.md", "LICENSE", "NOTICE"):
        source = REPO / name
        if source.is_file():
            shutil.copy2(source, STAGE / name)

    deps, python_min = read_dependencies()
    rendered = "\n".join(f'    "{dep}",' for dep in deps)
    (STAGE / "pyproject.toml").write_text(
        PYPROJECT.format(version=version, python_min=python_min, dependencies=rendered),
        encoding="utf-8",
    )


def main() -> None:
    version = read_version()
    print(f"[1/4] staging shamela-mcp {version}")
    stage(version)

    print("[2/4] validating manifest")
    result = npx("validate", str(STAGE / "manifest.json"))
    print("      " + (result.stdout.strip().splitlines() or ["valid"])[-1])

    DIST.mkdir(exist_ok=True)
    output = DIST / f"shamela-mcp-{version}.mcpb"
    if output.exists():
        output.unlink()

    print("[3/4] packing")
    npx("pack", str(STAGE), str(output))

    if not output.is_file():
        fail("pack reported success but produced no file")
    size_kb = output.stat().st_size / 1024
    print(f"[4/4] wrote {output.relative_to(REPO)} ({size_kb:.1f} KB)")
    print("\nInstall it by opening the file with Claude Desktop.")


if __name__ == "__main__":
    main()
